"use client";

import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import { AuthContext, AuthProvider } from "./contexts/AuthContext";
import "./globals.css";
import { darkTheme, lightTheme } from "./themes/theme";

import { ThemeProvider, CssBaseline } from "@mui/material";
import { ChangeEvent, useState } from "react";

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    let [useDarkTheme, setUseDarkTheme] = useState(false);
    let [theme, setTheme] = useState(useDarkTheme ? darkTheme : lightTheme);
    const changeThemeHandler = (target: ChangeEvent, currentValue: boolean) => {
        setUseDarkTheme(currentValue);
        setTheme(currentValue ? darkTheme : lightTheme);
    };

    return (
        <html lang="en">
            <head>
                <title>CeVai.app</title>
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <AuthProvider>
                <ThemeProvider theme={theme}>
                    <body id="__next">
                        <Navbar />

                        <CssBaseline />
                        {children}
                        <Footer />
                    </body>
                </ThemeProvider>
            </AuthProvider>
        </html>
    );
}
